// GENERATED by scripts/measure-groups.mjs --write. Do not edit by hand.
//
// What each group of tools costs to enable, in tokens of tool definitions, measured by starting
// the server on the `search` profile and diffing tools/list around an enable_tools call.
//
// unreal_list_tools reports these so a model can choose what to switch on knowing the price.
// `npm run measure:groups` fails when they drift, because a stale number here is worse than none.

/** Tool-definition tokens standing on the `search` profile before anything is enabled. */
export const SEARCH_BASELINE_TOKENS = 1536;

/** Tokens added by enabling each group. */
export const GROUP_COST_TOKENS: Record<string, number> = {
  core: 10882,
  ai: 294,
  anim: 1678,
  cine: 299,
  cpp: 840,
  data: 6098,
  edit: 5613,
  input: 1307,
  maintenance: 5777,
  materials: 2283,
  runtime: 3709,
  scene: 5631,
  ui: 2032,
  vfx: 698,
};

/** Everything enabled at once, for the rare job that genuinely needs the whole surface. */
export const ALL_GROUPS_TOKENS = 48676;

/** Naming the eight tools one Blueprint feature needs, instead of enabling the `core` group. */
export const FEATURE_SET_TOKENS = 5246;

/** Standing cost of each preset, enabled on its own from the `search` baseline. */
export const PRESET_COST_TOKENS: Record<string, number> = {
  diagnose: 10899,
  feature: 8414,
  ui: 6566,
  data: 7284,
  cpp: 5006,
};
